name: json
version: 0.8.0
date: 20/11/2014
description: Reading and Writing JSON

authors:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/

maintainers:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/

GAP: ">= 4.6"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: http://gap-system.github.io/json/
readme: http://gap-system.github.io/json/README
packageinfo: http://gap-system.github.io/json/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-system/json/releases/download/v0.8.0/json-0.8.0.tar.gz

abstract: 

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
