name: json
version: 1.0.2
date: 01/11/2016
description: Reading and Writing JSON

authors:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/

maintainers:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/

GAP: ">= 4.7.6"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: http://gap-packages.github.io/json/
readme: http://gap-packages.github.io/json/README
packageinfo: http://gap-packages.github.io/json/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/json/releases/download/v1.0.2/json-1.0.2.tar.gz

abstract: 

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
